### ISSUE TITLE
Add citation fille

### ISSUE THREAD

**Issue by eribean** [eribean/girth#118]
Github has a .cff file that allows users to see how to cite a repository. Add this file:

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/0000-0003-4925-7248
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2021-08-11
```
